import { JourneyData } from "../types/journey";

export const journeyData: JourneyData[] = [
  {
    id: 1,
    step: 1,
    title: "Powers of AI",
    skills: ["AI Fundamentals"],
    flag: "red",
  },
  {
    id: 2,
    step: 2,
    title: "Python Programming with AI, Cloud Fundamentals With AI",
    skills: [
      "Python",
      "Programming",
      "Data Types",
      "Skill 1",
      "Skill 2",
      "Python Programming",
    ],
    flag: "purple",
  },
  {
    id: 3,
    step: 3,
    title: "Python Programming with AI, Cloud Fundamentals With AI",
    skills: [
      "Python",
      "Programming",
      "Data Types",
      "Skill 1",
      "Skill 2",
      "Python Programming",
    ],
    flag: "purple",
  },
  {
    id: 4,
    step: 4,
    title: "Python Programming with AI, Cloud Fundamentals With AI",
    skills: [
      "Python",
      "Programming",
      "Data Types",
      "Skill 1",
      "Skill 2",
      "Python Programming",
    ],
    flag: "purple",
  },
  {
    id: 5,
    step: 5,
    title: "Python Programming with AI, Cloud Fundamentals With AI",
    skills: [
      "Python",
      "Programming",
      "Data Types",
      "Skill 1",
      "Skill 2",
      "Python Programming",
    ],
    flag: "purple",
  },
  {
    id: 6,
    step: 6,
    title: "Python Programming with AI, Cloud Fundamentals With AI",
    skills: [
      "Python",
      "Programming",
      "Data Types",
      "Skill 1",
      "Skill 2",
      "Python Programming",
    ],
    flag: "orange",
  },
  {
    id: 7,
    step: 7,
    title: "Python Programming with AI, Cloud Fundamentals With AI",
    skills: [
      "Python",
      "Programming",
      "Data Types",
      "Skill 1",
      "Skill 2",
      "Python Programming",
    ],
    flag: "purple",
  },
  {
    id: 8,
    step: 8,
    title: "Python Programming with AI, Cloud Fundamentals With AI",
    skills: [
      "Python",
      "Programming",
      "Data Types",
      "Skill 1",
      "Skill 2",
      "Python Programming",
    ],
    flag: "purple",
  },
  {
    id: 9,
    step: 9,
    title: "Python Programming with AI, Cloud Fundamentals With AI",
    skills: [
      "Python",
      "Programming",
      "Data Types",
      "Skill 1",
      "Skill 2",
      "Python Programming",
    ],
    flag: "orange",
  },
  {
    id: 10,
    step: 10,
    title: "Python Programming with AI, Cloud Fundamentals With AI",
    skills: [
      "Python",
      "Programming",
      "Data Types",
      "Skill 1",
      "Skill 2",
      "Python Programming",
    ],
    flag: "purple",
  },
];
